---
galaxy_info:
  author: "Tarik Amehri"
  description: "Deploy the Inception Docker Compose application."
  license: "MIT"
  min_ansible_version: "2.18"
  galaxy_tags:
    - "docker"
    - "wordpress"
dependencies: []
