---
galaxy_info:
  author: "Tarik Amehri"
  description: "Configure a UFW firewall for the application server."
  license: "MIT"
  min_ansible_version: "2.18"
  galaxy_tags:
    - "firewall"
    - "ufw"
dependencies: []
